//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseFirstEmpAndDept.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP
    {
        public int EmpID { get; set; }
        public string Ename { get; set; }
        public string JOB { get; set; }
        public decimal Salary { get; set; }
        public int DeptID { get; set; }
    
        public virtual DEPT DEPT { get; set; }
    }
}
